### ISSUE TITLE
incomplete_lq_factorization.cc not found

### ISSUE THREAD

**Issue by anaru** [tbennun/ceres-windows#1]
When trying to build this project in Visual Studio 2012, I got a build error. The files "incomplete_lq_factorization.cc" and "incomplete_lq_factorization.h" could not be found. I found that after removing references to these files from the project, I was able to build the library successfully.

**Comment by tbennun** [comment]
It seems that you are trying to build the library against master, whereas the wrapper is meant to build with version 1.10.0. In later revisions, the files you mentioned were removed, thus the build errors.
