### ISSUE TITLE
Want to know enabled features in this windows build

### ISSUE THREAD

**Issue by bigdimboom** [tbennun/ceres-windows#12]
Is OpenMP enabled?
Is GPU Sparse Matrix library enabled?

**Comment by tbennun** [comment]
To answer your questions:
1. OpenMP is enabled
2. The sparse matrix library used is Eigen (the default one). IIRC you can enable GPU support in Eigen somehow but I'm not sure it's compatible with ceres-solver.

For further questions about the build configuration, I suggest that you look at the configuration file: [internal/config.h](../blob/master/win/include/ceres/internal/config.h)

**Comment by bigdimboom** [comment]
I'm trying to build ceres with suitesparse, BLAS, LAPACK, but cmake can't find BLAS and  LAPACK. Do you know how to do it? And it's possible you create a branch for SUITESPARSE?

**Comment by tbennun** [comment]
You will have to install these libraries. It's an issue that is separate from ceres-solver.

Getting SUITESPARSE to work is much more complicated than getting ceres-solver to work with Eigen (I tried), so I'm not going to create a branch for that in the meantime. Sorry!
