### ISSUE TITLE
I can't build ceres

### ISSUE THREAD

**Issue by brentmorgan1987** [tbennun/ceres-windows#13]
I put eigen, glog, directories in the build directory.  Upon building in 2015 Visual Studio, I get ~27 errors.

Also: I made sure I'm using ceres-solver 1.12 and not 1.13 (most updated version).  I was not able to build 1.13 via CMake, so trying this route...

Thanks,
Brent

**Comment by tbennun** [comment]
Hi Brent,

Can you please post the error log here?

**Comment by tbennun** [comment]
Closed due to lack of response.
