### ISSUE TITLE
suitesparse contained or not?

### ISSUE THREAD

**Issue by woaik110** [tbennun/ceres-windows#2]
wondering that suitesparse isn't included here.

**Comment by tbennun** [comment]
SuiteSparse isn't included for the sake of minimalism. Is there any specific reason you think SuiteSparse in particular should be included?

There is also a separate branch with the smaller CXSparse.

**Comment by woaik110** [comment]
got it,thank you !
thought SuiteSparse faster than CXSparse.
I'm now trying to add SuiteSparse into ceres. Hope it works.
