### ISSUE TITLE
Update to Ceres Solver 2.0

### ISSUE THREAD

**Issue by PhuDoTuong** [tbennun/ceres-windows#23]
Could you guide me how to implement Ceres Solver 2.0 on Window 10 and Visual studio 2017?

**Comment by tbennun** [comment]
Upgrading the Visual Studio version is easy: you can open the latest solution and follow the upgrade instructions within VS.

Upgrading to Ceres Solver 2.0 requires loading the new version into the VS solution: this means that files that no longer exist need to be removed from the solution, and new files that are not compiled should be added. Just add all the new files from the folder to the project. The solution itself contains some macro definitions and settings that should be kept for the build to be successful, but the files can easily change.

Let me know if this works for you, and I'd be happy to accept a PR if it works.

**Comment by PhuDoTuong** [comment]
Thank you for your guides. I will implement them.

**Comment by PhuDoTuong** [comment]
Hello, I followed instructions of @Pyrokine at https://www.cnblogs.com/Pyrokine/p/14636228.html, and I used **glog 0.5.0** and **VS2017** instead. Also, @melhashash suggested using **vcpkg**.
