### ISSUE TITLE
ceres tests

### ISSUE THREAD

**Issue by r2d2bol** [tbennun/ceres-windows#4]
Not sure if this is a real issue or not, but I didn't see another way of contacting you. Thanks for providing these solution files. 

I was able to build ceres using the visual studio 2012 solution file.  I did not see any of the tests that come with ceres in the solution file.  Were these intentionally left out?

**Comment by tbennun** [comment]
Yes, they were intentionally left out due to the gtest and gflags dependencies. Any particular reason as to why they should be included?

**Comment by r2d2bol** [comment]
It would be nice to have a way to test the ceres solver build and verify it is working correctly.  If there is interest in this I could possibly add it and submit a pull request.

**Comment by tbennun** [comment]
It would be great if you added this as a pull request. There shouldn't be any complications beyond creating a new project that links against ceres.

Thanks!

**Comment by tbennun** [comment]
Any news?
