### ISSUE TITLE
Issue running helloworld

### ISSUE THREAD

**Issue by pokl90** [tbennun/ceres-windows#6]
Hi,

First time user, cannot get helloworld program to run. On compile I get  the error "Unable to start program 'C:.......\ceres-windows-master\Win32\Debug\libglob_static.lib'. 

I've extracted eigen, ceres-solver and glog into folders within 'ceres-windows-master', and am trying to run in VS2013 Express. I assume this is a quick enough fix, likely something silly on my end?

Any assistance would be much appreciated!

**Comment by tbennun** [comment]
When pressing the "Run" button (or pressing F5), Visual Studio compiles the "Start-up project" (the bold project in the Solution Explorer). You have to select the helloworld project, right click it, and click "set as start-up project".
