### ISSUE TITLE
When I use AutoDiffCostFunction, there are glog linking error

### ISSUE THREAD

**Issue by cvidkal** [tbennun/ceres-windows#7]
I compile in VS10 windows 10, and all things is well when I use sizedcostfunction, but there are following linking error when I use AutoDiffCostFunction.

unresolved external symbol "__declspec(dllimport) public: __cdecl google::base::CheckOpMessageBuilder::~CheckOpMessageBuilder(void)"

unresolved external symbol "__declspec(dllimport) public: class std::basic_string<char,struct std::char_traits<char>,class std::allocator<char> > \* __cdecl google::base::CheckOpMessageBuilder::NewString(void)"

unresolved external symbol "__declspec(dllimport) public: class std::basic_ostream<char,struct std::char_traits<char> > \* __cdecl google::base::CheckOpMessageBuilder::ForVar2(void)" 

unresolved external symbol "__declspec(dllimport) public: __cdecl google::base::CheckOpMessageBuilder::CheckOpMessageBuilder(char const *)

 unresolved external symbol "__declspec(dllimport) public: __cdecl google::LogMessageFatal::~LogMessageFatal(void)

unresolved external symbol "__declspec(dllimport) public: class std::basic_ostream<char,struct std::char_traits<char> > & __cdecl google::LogMessage::stream(void)

unresolved external symbol "__declspec(dllimport) public: __cdecl google::LogMessageFatal::LogMessageFatal(char const *,int)" 

unresolved external symbol "__declspec(dllimport) public: __cdecl google::LogMessageFatal::LogMessageFatal(char const *,int,struct google::CheckOpString const &)

**Comment by cvidkal** [comment]
This is a glog 0.3.4 bug on windows

**Comment by tbennun** [comment]
Good to know, thanks!

**Comment by olkham** [comment]
I was getting this error too but after 2 days of hair-pulling I found that I needed to add "GOOGLE_GLOG_DLL_DECL=
_MBCS"
to the project properties.

in VS2015 > C/C++ > Preprocessor > Preprocessor Definitions > GOOGLE_GLOG_DLL_DECL=
_MBCS

**Comment by brunobg** [comment]
Having the same problem here. Unfortunately what @oliver9523 suggested did not work (generates a bunch of syntax errors). Any tips?

**Comment by mribbons** [comment]
Thanks @oliver9523, this helped me. 
FYI if you are adding these in the configuration properties line, they are two separate options, so you need:

``
<existing options>;GOOGLE_GLOG_DLL_DECL=;_MBCS;
``

**Comment by tbennun** [comment]
@mribbons If this is something that can be added to the repository, could you please issue a pull request with the modification?

Thanks!
