### ISSUE TITLE
Unresolved external symbol

### ISSUE THREAD

**Issue by junliu-cn** [tbennun/ceres-windows#8]
6 unresolved external symbols in the following files:
ceres-windows-master\win\gradient_checking_cost_function.obj	 
ceres-windows-master\win\solver.obj	 
ceres-windows-master\win\trust_region_minimizer.obj

I don't know why and how to solve to this problem, can sombody give me a hint? Thanks.

**Comment by junliu-cn** [comment]
I finished to build the ceres lib using the newest ceres-windows.

**Comment by tbennun** [comment]
So, does this mean that the issue has resolved itself?

**Comment by xiaofeiwu** [comment]
I met similar errors, and the errors still exist with the latest version. I'm using VS 2015 in windows with the .sln file downloaded from the folder:

In total, there are four Unresolved external symbol, any cues on how to solve it will be appreciated.

Error: LNK2019	unresolved external symbol "void __cdecl ceres::internal::GetBestSchurTemplateSpecialization(int *,int *,int *)" (?GetBestSchurTemplateSpecialization@internal@ceres@@YAXPAH00@Z) referenced in function "public: virtual void __thiscall ceres::Solver::Solve(struct ceres::Solver::Options const &,class ceres::Problem *,struct ceres::Solver::Summary *)" (?Solve@Solver@ceres@@UAEXABUOptions@12@PAVProblem@2@PAUSummary@12@@Z)	helloworld_static	E:\Codes\ceres-windows-master\win\examples\ceres_static.lib(solver.obj)	1	

Error: LNK1120	1 unresolved externals	helloworld_static	E:\Codes\ceres-windows-master\Win32\Debug\helloworld_static.exe	1

**Comment by tbennun** [comment]
@xiaofeiwu Please use 'git clone --recursive' to obtain the correct version of ceres-solver. The function you are referring to was added after the latest release (v1.12.0), and is not supported in this solution.

@chrisluu I'm closing this issue. If there are still problems with ceres-windows, let me know and I'll reopen it.
