### ISSUE TITLE
Problems with GradientChecker Functionality

### ISSUE THREAD

**Issue by adam-hartshorne** [tbennun/ceres-windows#9]
I am getting unresolved external errors in relation to the gradient checker functionality. Using a simple example basically copying the example within gradient_checker_test.cc, where in this case TestTerm is just a copy of the "GoodTestTerm" function in the gradient_checker_test.cc

```
#define GLOG_NO_ABBREVIATED_SEVERITIES
#include "glog/logging.h"
 
#include "TestTerm.h"
 
nclude <iostream>
#include <fstream>
#include <memory>
#include <cmath>
#include <cstdlib>
#include <vector>
 
#include "ceres/cost_function.h"
#include "ceres/problem.h"
#include "ceres/numeric_diff_options.h"
#include "ceres/solver.h"
#include "glog/logging.h"
#include "ceres/gradient_checker.h"
 
using namespace std;
using ceres::AutoDiffCostFunction;
using ceres::CostFunction;
using ceres::Problem;
using ceres::Solver;
using ceres::Solve;
using ceres::GradientChecker;
using ceres::NumericDiffOptions;
 
int main(int argc, char** argv) {
// Test with 3 blocks of size 2, 3 and 4.
int const num_parameters = 3;
std::vector<int> parameter_sizes(3);
parameter_sizes[0] = 2;
parameter_sizes[1] = 3;
parameter_sizes[2] = 4;
// Make a random set of blocks.
std::vector<double*> parameters(num_parameters);
for (int j = 0; j < num_parameters; ++j) {
parameters[j] = new double[parameter_sizes[j]];
for (int u = 0; u < parameter_sizes[j]; ++u) {
parameters[j][u] = 2.0 * rand() - 1.0;
}
}
NumericDiffOptions test_diff_options;
GradientChecker::ProbeResults results;
TestTerm test_term(num_parameters, parameter_sizes.data());
GradientChecker good_gradient_checker(&test_term, NULL, test_diff_options);
 
good_gradient_checker.Probe(parameters.data(), 1e-9, &results);
std::cout << results.error_log;
 
 
}
```
 
provides the resultant warnings / build error even though the ceres.lib is definitely included (and I can run define a Problem etc etc etc fine within the same project and it builds), as obviously the following kind of error normally means you just haven't included the relevant library in your project.

**WARNINGS**
 
```
1>D:\Data\Documents\Visual Studio 2015\Projects\ceres-windows\ceres-solver\include\ceres/gradient_problem.h(108): warning C4251: 'ceres::GradientProblem::function_': class 'ceres::internal::scoped_ptr<ceres::FirstOrderFunction>' needs to have dll-interface to be used by clients of class 'ceres::GradientProblem'
1>  D:\Data\Documents\Visual Studio 2015\Projects\ceres-windows\ceres-solver\include\ceres/gradient_problem.h(108): note: see declaration of 'ceres::internal::scoped_ptr<ceres::FirstOrderFunction>'
1>D:\Data\Documents\Visual Studio 2015\Projects\ceres-windows\ceres-solver\include\ceres/gradient_problem.h(109): warning C4251: 'ceres::GradientProblem::parameterization_': class 'ceres::internal::scoped_ptr<ceres::LocalParameterization>' needs to have dll-interface to be used by clients of class 'ceres::GradientProblem'
1>  D:\Data\Documents\Visual Studio 2015\Projects\ceres-windows\ceres-solver\include\ceres/gradient_problem.h(109): note: see declaration of 'ceres::internal::scoped_ptr<ceres::LocalParameterization>'
1>D:\Data\Documents\Visual Studio 2015\Projects\ceres-windows\ceres-solver\include\ceres/gradient_problem.h(110): warning C4251: 'ceres::GradientProblem::scratch_': class 'ceres::internal::scoped_array<double>' needs to have dll-interface to be used by clients of class 'ceres::GradientProblem'
1>  D:\Data\Documents\Visual Studio 2015\Projects\ceres-windows\ceres-solver\include\ceres/gradient_problem.h(110): note: see declaration of 'ceres::internal::scoped_array<double>'

```

**BUILD ERRORS**
```
1>main.obj : error LNK2019: unresolved external symbol "public: __cdecl ceres::GradientChecker::GradientChecker(class ceres::CostFunction const *,class std::vector<class ceres::LocalParameterization const *,class std::allocator<class ceres::LocalParameterization const *> > const *,struct ceres::NumericDiffOptions const &)" (??0GradientChecker@ceres@@QEAA@PEBVCostFunction@1@PEBV?$vector@PEBVLocalParameterization@ceres@@V?$allocator@PEBVLocalParameterization@ceres@@@std@@@std@@AEBUNumericDiffOptions@1@@Z) referenced in function main
1>main.obj : error LNK2019: unresolved external symbol "public: bool __cdecl ceres::GradientChecker::Probe(double const * const *,double,struct ceres::GradientChecker::ProbeResults *)const " (?Probe@GradientChecker@ceres@@QEBA_NPEBQEBNNPEAUProbeResults@12@@Z) referenced in function main
1>D:\Data\Documents\Visual Studio 2015\Projects\OpenSubDiv_TestCurvatureMin\x64\Debug\TestJacobian.exe : fatal error LNK1120: 2 unresolved externals
```

**Comment by tbennun** [comment]
It seems that you did not link your project with ceres.lib in the solution. Just as a test, I created a new solution, compiled your file, and got the same link errors. Furthermore, when I replaced the code in the helloworld solution project (provided with the repository) with your code, everything compiled successfully.

**Comment by adam-hartshorne** [comment]
I have just tried to repeat your test replacing the code in helloworld and get the same error, using VS2015 x64 and Eigen 3.3.3.

Also, I 100% have got ceres.lib linked (in the original project I have a ceres "Problem" object that builds and runs fine, it is only when I try to use GradientChecker do I get the errors). 

Here a link to a clean vs2015 x64 project with just the aforementioned code. Perhaps there is some compiler setting I am missing or have incorrectly set? My concern is the warning that state I need a dll interface.

https://www.dropbox.com/pri/get/Public/TestGradient.zip?_subject_uid=2692145&w=AABmIdTh_aBAS6bq1lQakfjC0EVVQS1aamGBATCskbBugA

This produces exactly the same set of warnings and errors as the original post.

**Comment by tbennun** [comment]
Can you try taking one of the projects in the repository and switching the code? Maybe it's some preprocessor configuration or something similar.

**Comment by adam-hartshorne** [comment]
> Can you try taking one of the projects in the repository and switching the code? Maybe it's some preprocessor configuration or something similar.

Perhaps I am misunderstanding what you mean? From my reply above, is this not what I did here?

> I have just tried to repeat your test replacing the code in helloworld and get the same error, using VS2015 x64 and Eigen 3.3.3.

To be on the safe side, I have cleaned out my local copy, re-cloned from git, swapped out the code in helloworld.cc for the GradientChecker code.

I continue to still get the same errors if I build the hello_world i.e. non-static version. However, it does compile with helloworld_static.

**Comment by tbennun** [comment]
I found the source of the misunderstanding. I tried replacing the code in helloworld_static and it worked.

This is actually an issue in (or an intended feature of) ceres-solver. If you go to "include/ceres/gradient_checker.h", line 67, and replace:
```cpp
class GradientChecker {
```
with:
```cpp
class CERES_EXPORT GradientChecker {
```
Your code will then compile. Please report this as an issue in ceres-solver, because it also applies to other platforms.

**Comment by adam-hartshorne** [comment]
Thanks for your prompt responses and hard work looking into this. I can confirm that the GradientChecker test code using your port now builds on my machine.

I shall endeavor to report this bug to google.
